app:
    name: whatsapp-llm-bot
    port: 8080
    log_level: debug
whatsapp:
    session_path: /data/whatsapp_session
    allowed_groups:
        - 120363416151629681@g.us
        - 120363400902171371@g.us
    trigger_words:
        - '@sasi'
        - '@SASI'
ollama:
    url: http://192.168.1.245:11434
    model: gpt-oss:latest
    temperature: 0.7
    timeout: 300s
storage:
    type: memory
webhooks:
    - sub_trigger: '@family'
      url: http://192.168.1.132:5678/webhook/5a1a5bd0-0ff3-4393-9317-8da7f64c314e
    - sub_trigger: '@web'
      url: http://192.168.1.132:5678/webhook1/5a1a5bd0-0ff3-4393-9317-8da7f64c314e
